name: C/C++ CI

on: push

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install newer version of cmake
      uses: lukka/get-cmake@latest
    - name: Build using cmake
      run: mkdir build && cd build && cmake .. && cmake --build .
    - name: Move build results
      run: mkdir -p build/Analyzers/linux && mv build/Analyzers/*.so build/Analyzers/linux
    - name: Store build result as artifact
      uses: actions/upload-artifact@v4
      with:
        name: SENTanalyzer-linux
        path: build/Analyzers

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install newer version of cmake
      uses: lukka/get-cmake@latest
    - name: Build using cmake
      run: mkdir build && cd build && cmake .. && cmake --build .
    - name: Move build results
      run: mkdir -p build/Analyzers/macOS && mv build/Analyzers/*.so build/Analyzers/macOS
    - name: Store build result as artifact
      uses: actions/upload-artifact@v4
      with:
        name: SENTanalyzer-macos
        path: build/Analyzers

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install newer version of cmake
      uses: lukka/get-cmake@latest
    - name: Build using cmake
      run: mkdir build && cd build && cmake .. && cmake --build . --config Release
    - name: Move build results
      run: mkdir build/Analyzers/windows && mv build/Analyzers/Release/* build/Analyzers/windows
    - name: Store build result as artifact
      uses: actions/upload-artifact@v4
      with:
        name: SENTanalyzer-windows
        path: build/Analyzers
